name: CI/CD Pipeline

on:
  push:
    branches:
      - joseCastro_p2_dev
      - joseCastro_p2_base

jobs:
  static-codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt flake8 pytest
      - name: Lint
        run: flake8 restApp/
      - name: Run Unit Tests
        run: python -m pytest test/unit -v
    environment: develop

  build-and-push:
    needs: static-codecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Set image tag
        id: tag
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          echo "tag=${BRANCH}-1.0.0-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
      - name: Build Image
        run: docker build -t josedocker14/restapp:${{ steps.tag.outputs.tag }} .
      - name: Push Image
        run: docker push josedocker14/restapp:${{ steps.tag.outputs.tag }}
    environment: develop

  deploy-to-dev:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy Redis Container
        run: |
          docker stop redisService || true
          docker rm redisService || true
          docker run --name redisService -p 6379:6379 -d redis:alpine
      - name: Deploy restapp Container
        run: |
          redisIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)
          docker stop restapp || true
          docker rm restapp || true
          docker run --name restapp --add-host redis:$redisIP -p 5000:5000 -d josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}  # Aquí cambiamos myuser a josedocker14
      - name: Run Integration Tests
        run: python -m pytest test/integration -v
    environment: develop 

  deploy-to-prod:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Deploy Redis Container in Prod
        run: |
          docker stop redisService || true
          docker rm redisService || true
          docker run --name redisService -p 6380:6379 -d redis:alpine
      - name: Deploy restapp Container in Prod
        run: |
          redisIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)
          docker stop restapp || true
          docker rm restapp || true
          docker run --name restapp --add-host redis:$redisIP -p 5001:5000 -d josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}  # Aquí cambiamos myuser a josedocker14
      - name: Run Integration Tests in Prod
        run: python -m pytest test/integration -v
    environment: production


